env:
  browser: true
  es2021: true
extends:
  - 'eslint-config-discourse'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  # WARN: Indention rules may raise false positive, but seems like works well generally.
  #   Only turn back then when error raises, since the JS parser works worse.
  indent: off
  '@typescript-eslint/indent': [error, 2]
  linebreak-style: [error, unix]
  quotes: [error, single]
  semi: [error, always]
  max-len: [error, 120]
  no-multiple-empty-lines: [error, { max: 3 }]
  no-console: 'off'
  no-restricted-globals: 'off'
  '@babel/plugin-syntax-import-attributes/deprecatedAssertSyntax': 'off'
