env:
  browser: true
  es2021: true
extends:
  - 'eslint-config-discourse'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins: 
  - "@typescript-eslint"
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: 'off'
  no-restricted-globals: 'off'
  '@babel/plugin-syntax-import-attributes/deprecatedAssertSyntax': 'off'
