name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build

      - name: Configure Git # 配置Git
        env:
          DEPLOY_PRI: ${{secrets.DEPLOY_PRI}} # 这里就是刚刚配置的私钥了
          GIT_USERNAME: ${{ github.repository_owner }} #Github用户名，这里用了Actions自带的变量，也可以写死。
          GIT_EMAIL: ${{ github.repository_owner }}@user.github.com # 邮箱,可以写自己的邮箱。
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name 'BuildBot'
          git config --global user.email "$GIT_EMAIL"

      - name: Commit Build # 提交文档到Git仓库
        env:
          GIT_URL: 'git@github.com:Lhcfl/Linquebot_v2.git' # 项目的地址，注意要用SSH格式的。
        run: |
          cp package.json dist/
          cp package-lock.json dist/
          cp README.md dist/
          cd dist
          git init
          git remote add origin $GIT_URL
          git checkout -b build
          git add -A
          git commit -m "BUILD generated."

      - name: Push Build # 推送
        run: |
          cd dist
          git push origin HEAD:build --force
