name: ESLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'releases/**'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run lint
